name: Testes API - ServeRest

on:
  # Executa sempre que houver push na main
  push:
    branches:
      - main

  # Permite execução manual pelo GitHub
  workflow_dispatch:

  # Executa todos os dias às 08:00 - horário de Brasília
  # GitHub Actions utiliza UTC, portanto 08:00 BRT = 11:00 UTC
  schedule:
    - cron: "0 11 * * *"

jobs:
  testes-api:
    name: Executar testes Cypress
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"
          cache: "npm"

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes
        run: npm test -- --env baseUrl=https://serverest.dev

      - name: Salvar relatório dos testes
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes-api
          path: cypress/reports/
          if-no-files-found: ignore